<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CrossCutting\IoC\" />
    <Folder Include="CrossCutting\Mappings\" />
    <Folder Include="Data\Context\" />
    <Folder Include="Data\Repositories\" />
  </ItemGroup>

</Project>
